# -*- coding: utf-8 -*-
"""Binary Classifiaction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K5AjhqqpRoCyd_mr8E12tR2LxrenG5HI
"""

import sklearn
from sklearn import tree

features = [[2,300],[2,450],[8,200],[9,150]]
label=['sports-car','sports-car','Minivan','Minivan']
check = tree.DecisionTreeClassifier()
check=check.fit(features,label)
print(check.predict([[1,200]]))

import sklearn
from sklearn import tree

features = [[2,300],[2,450],[8,200],[9,150]]
label=['sports-car','sports-car','Minivan','Minivan']

check = tree.DecisionTreeClassifier()

check=check.fit(features,label)

print(check.predict([[8,50]]))